@startuml
left to right direction
'top to bottom direction

hide circle

img : <img src=https://avatars.githubusercontent.com/u/51136868{scale=0.1}>

package "p" {
    class A
    class B
    A -up[hidden]- B

    class Car implements Vehicle
    Object <|-- Car : (extends)

    Car ..right-> Fuel : (use)

    Car -- Person : Association (leasing)
    Car --o Garage : Aggregation
    Car *-- Engine : Composition
}

together {
    class C
    class "references other [[sequence.puml file]]" as D
}
class E
C ----- E

note left of B
  This is a [[https://www.youtube.com/watch?v=dQw4w9WgXcQ note]]
  with link
end note
@enduml