@startuml
left to right direction
'top to bottom direction

hide circle

img : <img src=https://avatars.githubusercontent.com/u/51136868{scale=0.1}>

package "p" {
    class A
    class B
    A -up[hidden]- B
}

together {
    class C
    class D
}
class E
C ----- E

note left of B
  This is a note
end note
@enduml